"""Guard the checked-in geometry catalogue against silent drift.

`edge/art/geometry_catalog.json` is generated by `scripts/gen_geometry_catalog.py`
from the vendored sprite library (`docs/SPRITE_ART_SYNC.md`, `docs/
SECTOR_SCENE_PHYSICAL_MODEL_PLAN.md` §9.4). An unguarded upstream sync can
retune a variant pool or a tier ladder without producing any Python error --
this test is what turns that into a loud CI failure instead of silently
shifting scene geometry.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
GENERATOR = ROOT / "scripts" / "gen_geometry_catalog.py"
CHECKED_IN = ROOT / "edge" / "art" / "geometry_catalog.json"

REFRESH_COMMAND = "python scripts/gen_geometry_catalog.py"


def test_geometry_catalog_matches_a_fresh_regeneration() -> None:
    assert CHECKED_IN.exists(), "edge/art/geometry_catalog.json must be checked in"
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=180,
    )
    assert result.returncode == 0, (
        "edge/art/geometry_catalog.json is stale relative to the vendored "
        f"sprite library. Refresh it with:\n    {REFRESH_COMMAND}\n"
        f"and commit the result.\n\n{result.stdout}\n{result.stderr}"
    )
