"""`ServiceProtocol` — the one typed service seam every consumer programs against (H16).

DESIGN §3/§14. This `typing.Protocol` captures exactly the surface `GameService` already
exposes: the single `apply` mutator plus every read-only `*_view` projection and the two
display helpers. It is **H16's one seam** — the TUI, the bot harness (`edge.bot`, WP60), the
sysop console, and the Phase-4 network/remote client all type against *this*, not the
concrete `GameService`, so a remote client is a drop-in once the wire exists (WP61+).

`GameService` is declared an implementation by a **static** assertion (`_assert_impl`, under
`TYPE_CHECKING` — no runtime import, no cycle): mypy fails the build if the class and this
protocol drift. The protocol is `@runtime_checkable` so a bot/test can also duck-type it.
Adding a public reader to `GameService` means adding it here in the same change (the contract).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

from edge.core import dto
from edge.core.config import GameConfig
from edge.core.enums import Commodity
from edge.core.events import Event
from edge.core.models import UniverseState
from edge.core.rules import Command


@runtime_checkable
class ServiceProtocol(Protocol):
    """The typed surface of the in-process game service (H16)."""

    # --- the single mutator --------------------------------------------------
    def apply(self, player_id: int, command: Command) -> tuple[Event, ...]: ...

    # --- read-only fog-of-war projections ------------------------------------
    def game_view(self, player_id: int) -> dto.GameState: ...
    def port_view(self, player_id: int, port_id: int) -> dto.PortDTO: ...
    def current_port_view(self, player_id: int) -> dto.PortDTO | None: ...
    def haggle_quote(self, player_id: int, commodity: Commodity,
                     counter_price: int) -> dto.HaggleQuote: ...
    def map_view(self, player_id: int, *, route_dest: int | None = ...,
                 full_graph: bool = ..., fit_width: int | None = ...) -> dto.LocalMapDTO: ...
    def computer_view(self, player_id: int) -> dto.ComputerDTO: ...
    def tavern_view(self, player_id: int) -> dto.TavernDTO: ...
    def market_view(self, player_id: int) -> dto.MarketDTO: ...
    def route_view(self, player_id: int, dst_sector: int, *,
                   full_graph: bool = ...) -> dto.RouteDTO: ...
    def route_legs_view(self, player_id: int, waypoints: list[int]) -> dto.RouteDTO: ...
    def engine_room_view(self, player_id: int) -> dto.EngineRoomDTO: ...
    def stardock_view(self, player_id: int) -> dto.StarDockDTO: ...
    def starbase_services_view(self, player_id: int) -> dto.StarbaseServicesDTO | None: ...
    def planet_view(self, player_id: int, planet_id: int) -> dto.PlanetDTO: ...
    def current_planet_view(self, player_id: int) -> dto.PlanetDTO | None: ...
    def surface_view(self, player_id: int, planet_id: int) -> dto.SurfaceDTO: ...
    def contact_view(self, player_id: int, species_id: int,
                     active_context: str = ..., active_subject: int | None = ...) -> dto.ContactDTO: ...
    def species_in_sector(self, player_id: int) -> int | None: ...
    def current_contact_view(self, player_id: int) -> dto.ContactDTO | None: ...
    def encounter_view(self, player_id: int) -> dto.EncounterDTO | None: ...
    def leads_view(self, player_id: int) -> list[dto.LeadDTO]: ...
    def messages_view(self, player_id: int) -> dto.MessagesDTO: ...

    # --- display helpers -----------------------------------------------------
    def describe_event(self, event: Event) -> str: ...
    def resolve_display_id(self, shown: int) -> int | None: ...

    # --- trusted accessors (dev tooling / bots read raw state) ---------------
    @property
    def state(self) -> UniverseState: ...
    @property
    def config(self) -> GameConfig: ...


if TYPE_CHECKING:  # static conformance: mypy fails if GameService drifts from the protocol.
    from edge.server.service import GameService

    def _assert_impl(service: GameService) -> ServiceProtocol:
        return service
