"""The injected geometry catalogue (plan §9.3, §9.4).

`edge/scene/` never builds or reads this data itself — construction and asset
loading live at the art/TUI seam (`edge/art/geometry_catalog.py`), driven by
`scripts/gen_geometry_catalog.py` and the checked-in
`edge/art/geometry_catalog.json`. This module only defines the plain,
immutable shapes the catalogue hands to the solver.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import Literal, Protocol

from edge.scene.geometry import CellBox


@dataclass(frozen=True, slots=True)
class LadderRung:
    """One authored tier of a laddered `(kind, subtype, axis, archetype)` sprite.

    `ink_min`/`ink_max` are a conservative *envelope* over the render seeds the
    game can produce for this rung — not a single exact figure — because
    variant choice is seeded independently of the natural box (plan §2.5).
    """

    tier_id: str
    index: int
    """0 = richest rung, ascending down the ladder."""
    natural: CellBox
    """The authored box; `col`/`row` are 0, `width`/`height` are exact."""
    ink_min: CellBox
    """Component-wise minimum ink bounds over the render sample."""
    ink_max: CellBox
    """Component-wise maximum ink bounds over the render sample."""
    ink_count_min: int
    ink_count_max: int
    render_cost: int
    """Measured, arbitrary integer units; no monotonicity is assumed by rung."""


@dataclass(frozen=True, slots=True)
class LadderKey:
    """The exact key laddered art varies by (plan §2.5): subtype plus rung
    index under-specifies it — a facing flip or a different species archetype
    silently selects different geometry."""

    kind: Literal["ship", "port"]
    subtype: str
    axis: Literal["horizontal", "vertical", "fixed"]
    archetype_id: str


@dataclass(frozen=True, slots=True)
class ContinuousYield:
    """Calibrated request-box -> visible-ink relationship for one procedural kind.

    Unlike `LadderRung`, this is *not* generated by
    `scripts/gen_geometry_catalog.py` — a procedural kind has no authored
    ladder to measure. It is calibration output (WP-SC05) and, per the plan's
    "no shipped defaults" rule for WP-SC02's tuning types, this record's shape
    is defined here but no instance ships with this commit.
    """

    kind: str
    ink_fraction_min: Fraction
    """Of the request box, conservative low."""
    ink_fraction_max: Fraction
    """Of the request box, conservative high."""
    min_extent: CellBox
    """Below this the kind is illegible and is rejected."""
    box_classes: tuple[CellBox, ...]
    """Descending; the anchor step-down ladder (plan §2.3)."""
    render_cost: tuple[int, ...]
    """Per box class, nondecreasing with box size."""


class ArtGeometryCatalog(Protocol):
    """Injected, immutable geometry lookup. `edge/scene/` only ever sees this
    protocol: construction and asset loading live at the art/TUI seam."""

    version: str

    def rungs(self, key: LadderKey) -> tuple[LadderRung, ...]: ...

    def continuous(self, kind: str) -> ContinuousYield: ...
